### PR TITLE
Change load_array() -> load_layers(), return xr.Dataset

### PR DESCRIPTION
**Pull request by gbrener**
Addresses #31 by changing `load_array()` to `load_layers()`, and having the function return an `xr.Dataset` object instead of `MLDataset`.

### CODE REVIEW

**Comment by PeterDSteinberg** [comment]
One variable naming thing related to this PR: 
 * Change the usage of `es` (formerly an `ElmStore` from Phase I approach) to `dset`.  There may also be places where `X` is used and `dset` would be more consistent with xarray/xarray_filters naming.

**Comment by gbrener** [comment]
@PeterDSteinberg, just made the es -> dset change.

**Comment by PeterDSteinberg** [comment]
Searching shows just one docstring using `X`: https://github.com/ContinuumIO/earthio/blob/8ac727307a9df3483b3b92ddfbb7e868570b33a3/earthio/tif.py#L168 here where `:X:` should be `:dset:`

**Comment by PeterDSteinberg** [comment]
Otherwise - can merge when tests pass.

**Comment by gbrener** [comment]
Ah, thanks for pointing that one out. Just pushed up the fixes; waiting on tests to pass.

**Comment by PeterDSteinberg** [comment]
With changes in the environment.yml / conda.recipe, can this line now be removed from [build_earthio_env.sh](https://github.com/ContinuumIO/earthio/blob/master/build_earthio_env.sh#L31)?

**Comment by gbrener** [comment]
Yes, I believe so - just pushed up the change.

**Comment by gbrener** [comment]
Merged despite package upload failure - that issue will be addressed in a separate PR.

**Pull request merged**
